### ISSUE TITLE
ulimit -v

### ISSUE THREAD

**Issue by renepickhardt** [renepickhardt/generalized-language-modeling-toolkit#23]
do we keep ulimit -v in run.sh ? 
I have the feeling the memory limit should somehow be configurable. but putting it to config.txt would not really be a nice workflow. Having it in run.sh is also kind of bad (we could make it an argument for run.sh which is set to a default value if not given)

**Comment by lschmelzeisen** [comment]
I don't know wether `ulimit` is needed at all. I just kept it in, as the old code had it. Configuring it would be nice. But storing this value in config.txt can't work since if we parse this in java, memory limitations by the system are already applied to our program. I like your cmd line option for `run.sh`.

**Comment by renepickhardt** [comment]
we need ulimit to run it on our internal infrastructure (actually as well as nice)
